### ISSUE TITLE
Goals v1.0.0 Release

### ISSUE THREAD

**Issue by eriestrisnadi** [IndomaximTechID/storaji-ui#2]
### Systems Need
- [x] Find VM/Anything for release server (@lowsprofile)
- [x] Migrating DB from beta server to release server (@lowsprofile)
- [x] Find a domain for website (@lowsprofile)

### Documentations Need
- [x] Create official website ([IndomaximTechID/storaji-website](https://github.com/IndomaximTechID/storaji-website))
- [ ] Documentation Usage for Consumer ([IndomaximTechID/storaji-website](https://github.com/IndomaximTechID/storaji-website))
- [ ] Documentation Developer for Contributors/Maintainers ([IndomaximTechID/storaji-website](https://github.com/IndomaximTechID/storaji-website))

### Feature Requests
- [x] Capability to add multiple order ([IndomaximTechID/storaji #1](https://github.com/IndomaximTechID/storaji/issues/1))
- [ ] Notifications detail success or fail for Login and Register ([IndomaximTechID/storaji #4](https://github.com/IndomaximTechID/storaji/issues/4))
- [x] Change password login
- [x] Product image
- [x] Profile edit
- [ ] Another currency support and Tax option ([IndomaximTechID/storaji #6](https://github.com/IndomaximTechID/storaji/issues/6))

#### Any other idea? Please open issue would be great!
